---
title: "Spatial Analysis of Russian Law Firms Naming"
author: "Pavel Syomin¹"
output:
  word_document:
    reference_doc: "journal-article/reference.docx"
bibliography: "journal-article/refs.bib"
csl: "journal-article/apa.csl"
link-bibliography: False  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<div custom-style="Affiliation">

¹Perm State University, Geographical faculty, Department of social and economic geography, Perm, Russia; e-mail: ntsp\@ya.ru

</div>

<div custom-style="Abstract">

**Abstract:** text.

</div>

<div custom-style="Keywords">

**Keywords:** naming; law firms; text embeddings; economic regions. 
</div>

# 1. Introduction

Geography of services, sometimes referred to as geography of service sector, is one of the essential parts of socio-economic geographical studies in Russia. Its history spans for several decades starting from the 1960s. Geography of services has economic and social dimensions, where the former is concentrated on the business aspects of the services, while the latter is focused on the issues of human well-being arising from the spatial structure of the relevant services [@Tkachenko2016]. Existing scientific literature on the geography of services in Russia covers a broad range of topics, e.g. education [@Shulgina2019], car rental [@Zyrianova2018], catering [@Preobrazhenskiy2018], medical care [@Kazantcev2022; @Panin2023; @Nikoloski2024], internet access [@Nagirnaya2015; @Zemtsov2022]. However, research on some problems is limited, with legal services being one of the notable examples of such a problem [@Tkachenko2016; @Moiseeva2016]. Despite the lack of attention from geographers, spatial aspects of law firms activity worth investigating for the several reasons. First, legal services can be categorized as business and producer services, acting as a representative case, and this category of services is important for the economic development in general, both in national or regional scale [@Hansen1993; @Faulconbridge2019]. Next, despite their relatively small direct economic impact, they have a great indirect importance as the intermediaries and helpers that contribute to the rule of law, social order, stability and predictability of social relations. Third, for regular citizens access to legal aid is important for the protection of human rights and ensuring the social justice, and in this context, the spatial aspects of law services are on par with the spatial issues of medical care [@Blacksell1988; @Blacksell1990].

Geographical research of services may focus on a variety of subjects. Some classical pathways of such research include analysis of centers and systems of service or of consumers' behavior, needs and demands, including estimation of influencing factors, investigation on the actual level of services provision, applied scientific work related to the management of social infrastructure [@Tkachenko2016]. Studies of firm names, sometimes also referred to as company names, brand names or just brands, is relatively unusual yet potentially fruitful method in the geography of services. Firm names are designed to distinguish the business from the competitors, to make an emphasis on the field of activity or its geographical area, inform about services supplied by a provider and corresponding benefits. Having these functions, brands convey a substantial portion of information in a short text message. Such information may be useful to discover the city's business landscape and consumer's perception of a particular city with its characteristic services [@Raento2001], analyze the trends common to a specific industry in a region [@Marjavaara2022] or the role of place as reflected in the toponyms in the business development and consumer attitudes [@Peluso2012; @Zhang2014; @Erdogan2016; @Noorda2019]. Company names represent the characteristics of businesses and thus may act as “meta-proxy” for a bulk of intertwined economic metrics. Such a complex nature makes them suitable for regions identification, especially in the case of vernacular regions [@Reed1976; @Liesch2015; @Vukosav2016; @Holtkamp2018]. Other interactions between places and brands, e.g. the contribution of commercial branding to place branding [@Florek2013] or its compliance with the latter [@BassolsiGardella2023] may also be of interest.

There are thousands of law firms in Russia [@Moiseeva2016]. Their names are likely to reflect some properties of local legal services market. The area of Russia is comprised of regions (constituent entities of the federation) that provide some sort of a commonly used spatial unit for geographical studies. Besides, economic geographers split the country into 11 economic regions [@Leyzerovich2010]. Each economic regions includes several constituent entities and is characterized by internal integrity, economic links between the companies, specialization and difference from the others. It can be hypothesized that the proximity of regions, as well as internal unity and economic links within the economic regions, leads to the similarity of law firms activity and, correspondingly, to the similarity of their naming. The overall aim of this study is to check whether this is true. To achieve this goal, a few research questions are asked and then answered based on the data on law firms names. These questions, or problems, are specified below.

Question 1 (Q1) is whether the neighboring regions have more similar law firm names that regions that do not share a common border. Question 2 (Q2) is a continuous extension of Q1: whether the geographical proximity of regions has an impact on the similarity of law firm names, i.e. whether the regions that are close to each other have more similar names, and vice versa. Question 3 (Q3) moves up from the level of regions to the level of economic regions: whether names withing the economic region are more similar compared to the names outside the region. Question 4 (Q4) is what naming strategies exist in Russia and how they are spatially organized. Question 5 (Q5) is a follow-up from the previous: are there strategies common or different within each economic region?

# 2. Materials and methods

## 2.1. Data

## 2.2. Methods

# 3. Results and discussion

# 4. Conclusion

<div custom-style="References-title">References</div>

<div id="refs"></div>


