---
title: "Технология использования открытых данных Федеральной налоговой службы России для экономико-географического анализа"
output: odt_document
bibliography: References.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Аннотация:
Ключевые слова:
A Method of Using Open Data Provided by Federal Tax Service of Russia in Spatial Economy Analysis
Abstract:
Keywords:

# Введение

Современные общественно-географические исследования часто опираются на работу с данными. Некоторые специалисты используют на агрегированную экономическую и демографическую статистику. Так, О. Л. Виноградова, анализируя изменение интенсивности земледелия в Европе, опирается на показатели стран в разные годы [@Виноградова2020]; Т. А. Балина с соавторам, рассматривая воспрос о территориях опережающего социально-экономического развития, приводит подсчёты по субъектам Российской Федерации [@Балина2021]; Г. М. Лаппо, описывая свою концепцию разнообразия городов, опирается на сведения о числе жителей в населённых пунктах в разные периоды времени [@Лаппо2019]. Другие исследователи используют большие массивы дезагрегированных данных, собирая их вручную в общедоступных источниках и используя сложные методы их обработки. Например, А. И. и М. В. Красновы для своей работы, посвящённой трансформации сети расселения в Псковской области, собирали публичные сведения о местоположении пользователей социальной сети «ВКонтакте» и открытые данные о поисковых запросах к «Яндексу» [@Красновы2020]. Есть работы, опирающиеся на обобщённую статистику, но использующие продвинутые методы её анализа. В частности, А. В. Федорченко взял данные Международной организации автопроизводителей, рассчитал на их основе индексы и дополнил их картографической визуализацией, что позволило эффективно проанализировать территориальные сдвиги в мировой автомобильной промышленности [@Федорченко2017]. «Большие данные» также проникают в общественно-географическую науку, что отметили ещё десять лет назад М. Грэм и Т. Шелтон [@Graham2013]. Недавний пример такого рода исследований — работа Вэй Лю и Вэньцзэ У, которые используют сведения о пользователях социальной сети WeChat для изучения связей между типом землепользования и деятельностью людей [@Liu2020]. Таким образом, общая тенденция такова: для исследований используются данные, хотя объём, тип, качество этих данных и технологии их обработки отличаются. 

Прежде чем использовать данные, необходимо их получить. Поиск качественных данных в достаточном количестве и их предварительная обработка во многом определяют результативность научной деятельности: проблемы в данных или в их анализе приводят к неправильным выводам, а сделать исследование при нехватке данных зачастую невозможно. Следовательно, источники данных и информационные технологии — это важный прикладной аспект общественной географии как науки. В. Н. Лаженцев, например, отмечает, что «совершенствование статистической науки в значительной мере предопределяет уровень экономико-географических исследований» [@Лаженцев2015], а К. Брунсдон рассуждает о важности изложения точных деталей анализа данных в контексте воспроизводимости географических исследований [@Brunsdon2016]. Практическая важность данных для исследований подтверждается, в частности, различными инициативами, связанными с обеспечением доступа к таким данным. Так, П. Арцбергер с соавторами ещё 20 лет назад предложили следующий принцип: результаты исследований, финансируемых на публичном уровне, должны быть максимально общедоступными, поскольку это, в частности, способствует новым исследованиям и тем самым увеличивает научный потенциал и отдачу от инвестиций в науку [@Arzberger2006], а Д. Кард с коллегами указывают на важность доступа учёных к административным данным, то есть информации, которая накапливается органами исполнительной власти при осуществлении их функций [@Card2010]. Для географических исследований особую роль играет такая разновидность данных, как пространственные данные, обеспечение доступа к которым в недавние годы также вызывает интерес во многих странах, включая США, Великобританию, государства ЕС, Сингапур [@Jozefowicz2020].

Типичным источником данных для исследований общественной географии России являются ресурсы Федеральной службы государственной статитстики (Росстата). К ним относятся, в частности, размещённые на официальном сайте этого органа данные официальной статистики, переписей и статистических обследований, база данных показателей муниципальных образований (БДМО) и единая межведомственная информационно-статистическая система (ЕМИСС). О. В. Кузнецова при исследовании структуры экономики российских регионов использует статистику валового регионального продукта и объёма отгруженных товаров [@Кузнецова2018]; Г. М. Фёдоров в своём анализе экономики регионов России на Балтике опирается на данные Росстата и Федеральной таможенной службы [@Fedorov2022]; С. Г. Сафронов изучает третичный сектор экономики России на базе данных Eurostat, Росстата и Федеральной налоговой службы [@Сафронов2021]; Ю. В. Петров на базе региональной, муниципальной статистики и данных иных органов власти формулирует предложения по социально-экономическому развитию юга Тюменской области [@Petrov2021]; М. А. Саранча оценивает развитие гостиничного и ресторанного бизнеса, задействуя результаты сплошного наблюдения Росстата за малым и среднем предпринимательством [@Sarancha2014]. Данные Росстата также используются для создания производных наборов данных, как в работе И. Ю. Пекер [@Peker2022]. Таким образом, большинство общественно-географических исследований не обходятся без применения данных Росстата как единственного источника информации или как одного из источников. 

Тем не менее, в ряде случаев данных Росстата недостаточно. Как следствие, возникает необходимость в альтернативных источниках информации, которые либо дополняют официальную статистику, либо заменяют её. Причины этого бывают разные. В некоторых случаях альтернативные источники информации используются для проверки или корректировки данных Росстата. Например, Р. А. Бабкин, основываясь на данных сотовых операторов, доказывает, что официальная численность населения московской агломерации занижена примерно на 10% из-за погрешности и инертности статистического учёта и «двудомности» значительной части москвичей [@Babkin2020]. Другая, более частая причина — отсутствие нужных сведений. Например, К. В. Ростислав, анализируя влияние местоположения на прибыльность предприятий, учитывает только организации с численностью работников меньше 250 человек и для проверки этого условия использует открытые данные ФНС России, так как Росстат такие сведения не предоставляет [@Rostislav2021]. С. С. Лачининский с соавторами оценивает спрол городских территорий Санкт-Петербурга с опорой на спутниковые снимки Landsat, так как на базе сведений официальной статистики провести необходимые подсчёты невозможно [@Lachininskiy2023]. К преимуществам альтернативных источников данных относят повышенную точность и своевременность [@Воробьев2021], более высокое пространственное и временное разрешение [@Бабкин2021], возможность точного и детального анализа на микроуровне [@Бочкарёв2017], отмечая при этом несвоевременность, неполноту и потенциальную недостоверность официальной статистики [@Кузьминов2021]. Альтернативные источники данных дают доступ к генеральной совокупности, вследствие чего «отпадает необходимость в использовании выборочных, агрегированных и косвенных» источников сведений [@Блануца2017]. При использовании методов машинного обучения, что также становится актуальным в современной географии, важны объём выборки, дезагрегированность, количество признаков в данных, что также побуждает обращаться к альтернативным источникам [@Ростислав2020]. Таким образом, хотя традиционные статистические сведения по-прежнему важны в общественно-географических исследованиях, а порой незаменимы, есть нарастающая потребность в других информационных ресурсах. Запрос со стороны исследователей идёт на повышение объёма, оперативности предоставления, точности, пространственного и временного разрешения, расширение набора доступных показателей, а также на возможность валидации статистических сведений. Он проявляется и в части традиционных научных методов, так и методов, связанных с машинным обучением, хотя более актуален именно для последних, наиболее чувствительных к объёму данных, их дезагрегированности, детализации, удобным форматам представления.

Одним из альтернативных источников информации, которые входят в обиход географов-обществоведов, являются административные данные Федеральной налоговой службы России (ФНС России), которые публикуются на её официальном сайте или связанных с ним ресурсах. Используются, в частности, сведения о доходах физических лиц [@Петров2021], о налоговых поступлениях в разрезе субъектов федерации или видов экономической деятельности [@Ростислав2020; @Сафронов2021], о среднесписочной численности работников организаций [@Ростислав2021], о количестве учтённых жилых помещений [@Lachininsky2021], о количестве малых и средних предприятий [@Гуменюк2022]. Внимание исследователей к данным, публикуемым ФНС России, связано, по-видимому, с многофункциональностью этого органа власти, из-за которой он собирает огромный объём информации о разных сторонах российской экономики (хозяйствующие субъекты, имущество, доходы, расходы). Как правило, ФНС России публикует сводную (агрегированную) информацию. Тем не менее, есть несколько наборов данных, содержащих дезагрегированные (исходные, первичные, «сырые») данные, из которых наибольшее внимание привлекает реестр субъектов малого и среднего предпринимательства, который полностью и регулярно размещается на сайте службы и содержит сведения о конкретных организациях и индивидуальных предпринимателях.

В статье представлена технология, позволяющая использовать некоторые наборы открытых данных Федеральной налоговой службы в качестве источника информации об организациях и индивидуальных предпринимателях, осуществляющих деятельность в том или ином месте в той или иной сфере экономики, а также о доходах, расходах и численности работников этих организаций. Несмотря на свою относительную концептуальную простоту, технология является достаточно универсальной и потенциально полезной, особенно учитывая нехватку наборов данных для исследований, особенно в машиночитаемом виде. Она позволяет получить данные за период с середины 2016 года с детализацией по месяцам, отдельным населённым пунктам (городским и сельским) и конкретным кодам классификатора видов экономической деятельности. Кроме того, технология обеспечивает детализацию до конкретных физических лиц и организаций, что открывает возможности для углублённого анализа (например, миграции отдельных компаний и сопутствующая динамика). Полнота сведений отличается в зависимости от цели использования:
а) применительно к малому и среднему предпринимательству технология позволяет получить полный список соответствующих организаций и индивидуальных предпринимателей;
б) применительно к экономике в целом технология позволяет получить выборку организаций, которая является репрезентативной в пространственном аспекте и в аспекте классификации по видам экономической деятельности.

В следующем разделе, «Данные и методы», приводится описание источников «сырых» данных и методов их обработки в общем виде, то есть на концептуальном уровне формулируется алгоритм, составляющий суть технологии. Кроме того, даётся краткое описание авторской реализации данной технологии и  инструментов, использованных для этой реализации, а также ссылка на исходный код компьютерной программы. Раздел «Результаты» описывает результаты пробного использования технологии для получения информации о компаниях и физических лицах, осуществляющих деятельность в сфере юридических услуг, а также результаты валидации технологии с использованием статистики Росстата. В разделе «Обсуждение» анализируются возможные варианты и ограничения использования технологии, а также некоторые аспекты её практической реализации. «Выводы» подводят итоги статьи.

# Данные и методы

Исходные данные
В качестве исходных данных, которые обрабатываются алгоритмом, используются три набора открытых данных Федеральной налоговой службы (ФНС) России.
Первый, основной — это набор «Единый реестр субъектов малого и среднего предпринимательства». Технически он представляет собой коллекцию zip-архивов xml-файлов. Zip-архив представляет собой «срез» (выгрузку) из реестра по состоянию на определённую дату. Одна дата представлена ровно одним архивом. В каждом архиве находится множество (несколько тысяч) xml-файлов. Каждый xml-файл, в свою очередь, содержит в себе информацию о множестве (обычно ровно 900) организациях или индивидуальных предпринимателях, включённых в реестр. Одна организация или один индивидуальный предприниматель в xml-файле представлен элементом «Документ». Отдельные характеристики организации или предпринимателя (название, ИНН, коды ОКВЭД, местонахождение и другие) представлены как вложенные элементы и их атрибуты. Общая схема указанной структуры данных представлена на рисунке.
Указанный набор открытых данных доступен за период с августа 2016 г. по настоящее время. Новые выгрузки публикуются ежемесячно. Таким образом, на момент написания статьи доступно около 85 выгрузок. Каждая выгрузка (архив) имеет объём от 2 до 3 Гб в сжатом виде и от 30 до 50 Гб в распакованном. Общий объём исходных данных этого набора в несжатом виде, таким образом, оценивается в несколько терабайт (тысяч гигабайт), что приводит к необходимости использования специальных методов оптимизации и конкретных технологических решений, адаптированных к эффективной работе с «большими данными», о которых будет сказано ниже.
Второй, вспомогательный набор — это «Сведения о суммах доходов и расходов по данным бухгалтерской (финансовой) отчетности организации». Технически он также представляет собой коллекцию zip-архивов xml-файлов. Каждый архив представляет собой выгрузку на определённую дату, содержит несколько тысяч xml-файлов, каждый из которых, в свою очередь, содержит информацию о нескольких сотнях организаций. Данные обновляются с разной периодичностью, но фактическая частота обновления — ежегодно: если в течение года публикуется несколько выгрузок, то все они содержат данные за предыдущий год и отличаются лишь в небольшой части записей, что, вероятно, представляет собой исправление ошибок в ранее размещённых выгрузках. В момент подготовки статьи были доступны выгрузки с 2019 г. В текущий момент выгрузки за предыдущие даты исчезли с сайта ФНС России, и причины этого непонятны.
Третий набор, также вспомогательный — «Сведения о среднесписочной численности работников». Его структура и периодичность обновления аналогичны предыдущему. В момент подготовки статьи были доступны выгрузки с 2019 г. В текущий момент выгрузки за предыдущие даты исчезли с сайта ФНС России, и причины этого непонятны.
В каждом из трёх наборов указан ИНН организации или индивидуального предпринимателя. Поскольку ИНН является уникальным идентификатором, то он позволяет связать сведения из трёх наборов данных.
Открытые данные по определению являются официальными и свободно распространяемыми, что позволяет рассматривать их как достаточно надёжный и удобный для использования источник информации. Тем не менее, количество данных и формат их распространения порождают необходимость использовать специальные методы обработки, о которых говорится далее.
Общий алгоритм обработки данных
Шаг 1. Загрузка данных из источника на локальный компьютер или в облачное хранилище. Смысл этапа — получить собственную копию исходных данных, которая будет обрабатываться. Этот шаг выполняет две функции: во-первых, ускоряет дальнейшую обработку за счёт того, что исходные архивы уже загружены на устройство, где они будут обрабатываться, или в облачное хранилище, где передача данных между сервисом хранения и сервисом вычисления происходит быстро; во-вторых, страхует от внезапного исчезновения исходных архивов и позволяет проводить обработку данных даже в том случае, если они будут сняты с публикации, как случилось с двумя вспомогательными наборами. Под облачным хранилищем может пониматься как пользовательский сервис хранения данных наподобие «Яндекс-диска», так и специализированное объектное хранилище с S3-совместимым интерфейсом наподобие Object Storage Яндекс-облака.
Шаг 2. Фильтрующее извлечение данных. Смысл этапа — извлечь информацию из архивов, выбирая при этом только те сведения, которые необходимы конечному пользователю данных. Чтобы понять преимущество данного этапа, нужно сравнить его с более классическим алгоритмом. Более классический вариант работы с xml-файлами, запакованными во множество архивов, выглядел бы следующим образом: извлечение xml-файлов из архива — конвертация xml-файлов в табличный формат — сохранение табличных данных — фильтрация табличных данных. Несмотря на «каноничность» такого решения, у него есть существенный недостаток: оно приводит к формированию большого количества промежуточных файлов, которые занимают большой объём хранилища, но не имеют практической ценности. При небольшом объёме исходных данных проблема промежуточных файлов несущественна, однако, как говорилось выше, объём первого, самого крупного набора данных в распакованном виде оценивается в несколько терабайт, и примерно столько же будут занимать промежуточные файлы. Как следствие, для реализации алгоритма требуется либо компьютер, выходящий за рамки стандартного потребительского класса, либо аренда облачных ресурсов. И то, и другое дорого и неоптимально с точки зрения результата. Фильтрующее извлечение позволяет распаковывать и извлекать данные «на лету», сводя к минимуму образование промежуточных файлов. Сохраняются при этом только те сведения, которые необходимы конечному пользователю. В частности, можно отфильтровать данные по коду ОКВЭД или субъекту федерации. Итоговое табличное представление данных является более компактным, чем исходный набор xml-файлов, примерно в 10–20 раз, а при фильтрации — и более.
Шаг 3. Агрегация данных. Смысл этапа — построить хронологию на основе повторяющихся записей. Исходные данные представляют собой выгрузки с определённой периодичностью. За время, прошедшее между выгрузками, информация о конкретной организации или конкретном индивидуальном предпринимателе могла остаться прежней, в результате чего в табличном представлении может остаться несколько строк с одинаковыми данными, различающиеся только временной меткой. Суть агрегации в том, чтобы заменить несколько повторяющихся строк одной, для которой будет указано время актуальности. Поскольку проверка того, изменилась ли информация или нет, должна учитывать потенциальные несущественные технические изменения и ошибки в исходных данных, то агрегация также включает в себя базовую подготовку данных: приведение регистра, проверку написания кодов и номеров и тому подобное.
Шаг 4. Геопривязка данных. Смысл этапа — для каждой организации или каждого индивидуального предпринимателя указать адрес, координаты и код ОКТМО. Исходные данные содержат информацию об адресе согласно Федеральной информационной адресной системе исходя из административно-территориального деления: субъект федерации, район, город, населённый пункт. В процессе геопривязки адреса нормализуются. Исходя из нормализованного адреса, указывается код ОКТМО и географические координаты.
Шаг 5. Обогащение данных. На этом этапе базовая информация об организациях и индивидуальных предпринимателях дополняется вспомогательной. В качестве источника вспомогательной информации используются второй и третий наборы данных. Опционально возможно использовать и другие источники данных. Ключевым условием является наличие в дополнительных источниках данных ИНН, поскольку именно он является уникальным идентификатором.
Шаг 6 (опциональный). Подготовка панельного представления. Суть этапа — преобразовать полученные данные в более привычный формат. После прохождения описанных выше пяти этапов данные представлены в виде строк, каждая из которых содержит сведения о хозяйствующем субъекте за определённый период времени, причём период времени может быть разным. При этом начало и конец периода указаны с точностью до месяца и года. В географических исследованиях более применимы данные, которые характеризуют положение дел на какой-то год. Таким образом, в ходе данного шага данные преобразуются так, что для каждой организации или индивидуального предпринимателя за каждый год указывается преобладающее значение той или иной характеристики. Например, если в течение 10 месяцев в году организация находилась в Москве, а остальные два месяца — в Московской области, то считается, что весь год организация находилась в Москве.
Реализация алгоритма
Описанный выше алгоритм реализован как несколько скриптов на языке программирования Python. Для хранения данных использовался локальный компьютер. Для извлечения данных использовались стандартные модули Python и библиотека lxml. Агрегация данных производилась с помощью системы для обработки больших данных Spark. Геопривязка осуществлялась с помощью специально разработанного алгоритма на базе двух справочных таблиц: одной по городам России, другой по населённым пунктам России (преимущественно сельским). Обогащение данных и создание панели также реализованы как скрипты на Python. Исходный код опубликован по адресу: ...
Валидация данных
Включает в себя две стадии. Первая — это формальная валидация: проверка типа данных и заполненности разных полей итоговой таблицы. Вторая — это содержательная валидация. Очевидно, что реестр субъектов малого и среднего предпринимательства не содержит информации обо всех организациях в России и представляет собой выборку из него, причём в общем смысле не репрезентативную. Тем не менее, есть основания полагать, что выборка всё же является достаточно репрезентативной в отношении географического положения хозяйствующих субъектов и видов деятельности. Соответственно, на второй стадии валидации важно сравнить получившийся набор данных с генеральной совокупностью. В качестве генеральной совокупности используется статистический регистр Росстата. Для сравнения берётся сводная информация о количестве организаций в разрезе субъектов федерации и кодов ОКВЭД за 2019–2022 гг. Поскольку при географических исследованиях важным зачастую является не точное совпадение абсолютных чисел (которое в данном случае недостижимо), а совпадение относительного положения тех или иных мест или категорий, то в качестве метрики для оценки используется ранговый коэффициент корреляции Спирмена в разрезе регионов или кодов ОКВЭД.
Результаты
Для тестирования алгоритм был запущен со следующими параметрами:
1) временной диапазон входных данных — с августа 2016 г. по ноябрь 2023 г. (все доступные на сайте ФНС России данные);
2) группа ОКВЭД — «А» (сельское, лесное хозяйство, охота, рыболовство, рыболовство). Она объединяет несколько отраслей экономики, которые в экономическое географии обычно рассматриваются изолированно. Тем не менее, поскольку при тестировании важно показать принцип работы алгоритма (извлечение по группам или кодам ОКВЭД), то было отдано предпочтение именно классификатору, а не группировке, принятой в научной сфере. Кроме того, такой вариант запуска показывает, что алгоритм позволяет одновременно извлечь сведения о нескольких связанных отраслях экономики.
Сводная статистика по работе алгоритма
Примерное время подготовки набора данных составило 15 часов, вычисления выполнялись на обычном персональном компьютере с примерно 300 Гб свободного места на диске и 16 Гб оперативной памяти.
На схеме показано уменьшение количества обрабатываемых данных от шага к шагу алгоритма. Входные данные — это 88 архивов суммарным объёмом 193 Гб в сжатом виде, содержащие около 600 тысяч xml-файлов и 550 миллионов исходных записей. После фильтрующего извлечения промежуточный набор данных состоял из 88 csv-файлов объёмом 6 Гб и суммарно содержал 15 миллионов строк. В результате агрегации получился один датасет (csv-файл) объёмом 133 Мб, содержащий 500 тысяч строк. Геопривязанный датасет содержит почти столько же строк (их количество немного уменьшилось из-за того, что часть адресов после нормализации оказалась дублями) и занимает чуть больше 200 Мб (объём вырос из-за добавления нормализованных адресов к «сырым»). Панельное представление также является одним csv-файлов объёмом около 600 Мб, содержащим несколько миллионов строк (панельное представление менее компактно, так как данные, не меняющиеся год от года, дублируются для сохранения временной структуры). Таким образом, в результате обработки объём данных уменьшился с нескольких терабайт до нескольких сотен мегабайт (с промежуточными файлами — нескольких гигабайт), и из полного списка организаций, содержащего несколько сотен миллионов записей, было выбрано несколько сотен тысяч интересующих. Кроме того, данные обогатились геопривязкой и кодами ОКТМО. В результате получился компактный датасет, который можно обработать на обычном компьютере без установки специальных программ для работы с «большими данными» — в отличие от исходного набора данных на сайте ФНС России.
Итоговый датасет содержит информацию о 300 тысячах индивидуальных предпринимателей и 100 тысячах огранизаций, осуществляющих или осуществлявших деятельность в сфере сельского, лесного хозяйства, охоты, рыболовства и рыбоводства. Он позволяет искать, группировать, агрегировать и анализировать данные в нескольких разных аспектах. Приведём основные из них.
Временная динамика
Набор данных охватывает период с 2016 по 2023 г. с точностью до месяца. Соответственно, он позволяет проследить динамику численности хозяйствующих субъектов в том или ином регионе или той или иной сфере деятельности. На графике 1.1 показаны первые 10 регионов с наибольшим количеством организаций в группе А за каждый месяц из анализируемого периода, а на графике 1.2 — изменение числа хозяйствующих субъектов в отдельных укрупнённых сферах экономики: сельское хозяйство, лесное хозяйство, охота, рыболовство и рыбоводство.
Пространственная структура по субъектам федерации
Набор данных охватывает все субъекты России, для которых имеются исходные данные. Благодаря нормализованному (приведённому в соответствие с Конституцией России) названию субъекта федерации данные можно легко агрегировать и тем самым подсчитать количество хозяйствующих субъектов в каждом регионе в целом или по отдельным кодам ОКВЭД. На картограмме 2.1 показано распределение регионов по количеству хозяйствующих субъектов в сфере сельского хозяйства, а на картограмме 2.2 — лесного хозяйства. Видно, что география указанных отраслей ожидаемо отличается. Глубокая детализация по кодам ОКВЭД позволяет выбрать и визуализировать распределение хозяйствующих субъектов по узким и довольно специфичным кодам. Так, картограмма 2.3 показывает распределение организаций с кодом 1.6.22 «Выращивание подсолнечника», а картограмма 2.4 — (что-то про лесное хозяйство).
Пространственная структура по населённым пунктам
Набор данных содержит информацию о местоположении хозяйствующих субъектов с точностью до населённого пункта, а также координаты этих пунктов и коды ОКТМО соответствующих муниципальных образований. Это позволяет агрегировать данные по населённым пунктам, визуализировать их на картах и схемах, а также связывать со статистикой по муниципальным образованиям.
На картограмме 3.1 показано распределение организаций по территории России в виде точек, изображающих населённые пункты. Картограмма 3.2 представляет собой часть картограммы 1 и показывает число и соотношение видов организаций в г. Екатеринбурге и окрестностях.
В таблице 3.2 приведены результаты простейшего анализа данных во взаимосвязи с внешними ресурсами: количество организаций в городах в пересчёте на тысячу жителей.
Отслеживание отдельных хозяйствующих субъектов
Набор данных детилизирован до отдельных организаций и индивидуальных предпринимателей, что позволяет проследить динамику каждого из них, а также агрегировать информацию об изменениях. В таблице 4.1 показано число изменений юридического адреса у хозяйствующих субъектов. На картограмме 4.2 показаны «регионы-доноры» и «регионы-реципиенты» хозяйствующих субъектов за период с 2017 по 2021 г.
Анализ наименований
Набор данных содержит сведения о наименованиях организаций. Наименования сами по себе могут быть ценным источником информации, если обрабатывать их с использованием методов автоматизированной обработки текстов. На схемах 5.1 и 5.2 показаны «облака слов» из названий организаций в сфере сельского и лесного хозяйства, соответственно.
Дополнительные атрибуты
Расширение набора данных за счёт информации о численности работников организаций и доходах с расходами позволяет перейти от простого подсчёта к «взвешенному» подсчёту и анализировать территориальное, временное или структурное распределение с учётом прибыли и числа занятых. На схемах 6.1–6.3 показано распределение соответственно числа организаций, их суммарной прибыли и числа работников в сфере «сельское хозяйство».
Обсуждение
Рассуждая о предложенном алгоритме, необходимо обратить внимание на два его аспекта: техническую ценность и исследовательскую ценность. Говоря об исследовательской ценности, важно обратить внимание на два аспекта: частный (о применимости получаемого датасета для исследований в области малого и среднего предпринимательства) и общий (возможность использования данных для выводов об экономике в целом).
Техническая ценность предложенного алгоритма связана с тем, что он позволяет достаточно эффективно (без существенных финансовых затрат и за сравнительно короткий период времени) обработать массивы исходных данных ФНС России и представить их в виде, подходящем для географических исследований, то есть плоских таблиц с геопривязкой. Благодаря алгоритму и его прикладной реализации несколько терабайт исходной информации фильтруются и компактно представляются в виде относительно небольшой таблицы, которую можно использовать на стандартном компьютере без облачных технологий и инструментов работы с большими данными. Программный код находится в открытом доступе и может использоваться любым специалистом, владеющим языком программирования Python, для создания собственных производных решений.
Исследовательская ценность алгоритма и набора данных в контексте исследований малого и среднего предпринимательства заключается в том, что датасет представляет собой максимально полный и детализированный из доступных набор сведений об организациях и предпринимателях, относящихся к МСП. Он объединяет в себе три измерения: пространственное (с точностью до населённого пункта), временное (с точностью до месяца или года) и структурное (с точностью до отдельных кодов ОКВЭД) и представлен в наиболее дезагрегированном виде: в отличие от традиционных статистических данных, исходная единица в нём — это конкретный хозяйствующий субьект. Таким образом, набор данных может рассматриваться как квази-источник первичных статистических сведений. Поскольку вся представленная в нём информация об организациях представляет собой изъятие из режима налоговой тайны и по закону имеет открытый характер, то использование датасета не нарушает права частных лиц и законодательство России.
Помимо организаций, набор данных содержит также сведения об индивидуальных предпринимателях. Его ценность ниже, так как для них отсутствуют дополнительные данные о доходах, расходах и числе работников. Кроме того, если информация о названиях организаций обладает самостоятельной исследовательской ценностью, то имена физических лиц такой ценностью вряд ли характеризуются. Кроме того, сведения в датасете относятся к информации об определённом физическом лице, то есть являются персональными данными, что поднимает вопрос о юридических рисках их использования, особенно в свете ужесточения законодательства о персональных данных.
Вопрос об исследовательской ценности набора данных для анализа экономики России в целом более сложен. С одной стороны, очевидно, что субъекты малого и среднего предпринимательства — это не все хозяйствующие субъекты в России. Более того, понятно также, что они не являются случайной выборкой из генеральной совокупности таких субъектов, поскольку отобраны по конкретным критериям: число работников и доход. Иначе говоря, реестр и производный от него датасет содержат сведения только о части фирм, причём о самых небольших из них, а крупный бизнес при этом выпадает из поля зрения. Тем не менее, есть некоторые доказательства, что как минимум отчасти такой датасет может быть репрезентативным в географическом и структурном отношении. Как показано в разделе с валидацией, агрегированная статистика по регионам и группам деятельности, полученная на базе датасета, высоко скоррелирована с данными, полученными на базе статистического регистра Росстата, который является генеральной совокупностью. Коэффициент корреляции не очень высокий разве что в отдельных специфических группах, что объяснимо (большая часть образовательных организаций и организаций в сфере публичной власти — не частные, а государственные или муниципальные), в остальных случаях он превышает 0.9. Иначе говоря, датасет на базе реестра МСП (как выборка) хорошо скоррелирован с генеральной совокупностью в географическом (с точностью до регионов) и структурном (с точностью до большинства групп ОКВЭД) разрезах. Это позволяет говорить о его репрезентативности как минимум в этих двух аспектах. Так, при любом ранжировании регионов или видов деятельности результат, полученный на базе реестра МСП, будет в основном совпадать с результатом, полученным на базе сплошного обследования всех фирм в России. Это не говорит о том, что датасет репрезентативен в более «узких» разрезах (на уровне отдельных кодов ОКВЭД или конкретных населённых пунктов), но в отсутствие иных источников информации позволяет использовать его в качестве первого — и наиболее адекватного из доступных — приближений к генеральной совокупности в тех случаях, когда требуются данные по экономическим субъектам в России с высокой детализацией. Тем не менее, вопрос о репрезентативности желательно при каждом конкретном исследовании анализировать отдельно.
Два сопутствующих вопроса, касающихся исследовательской ценности в любом аспекте, касаются соответствия между номинальным и реальным положением дел. В реестре МСП указаны юридический (номинальный) адрес и номинальный же код ОКВЭД. Очевидно, что они могут отличаться от реальных. Также следует заметить, что отличия могут быть разной степени выраженности в зависимости от места и вида деятельности. Так, можно предположить, что место регистрации фирмы будет как минимум отчасти объясняться налоговыми или престижными соображениями, а место регистрации фирм, осуществляющих деятельность в интернете или в нескольких регионах, будет мало связано с местом их регистрации. Автору не известны какие-либо исследования на эту тему, равно как и надёжные и легко реализуемые методы, позволяющие проверить соответствие между номинальными данными и реальностью. Понятно лишь то, что датасет и любые производные от него статистические данные будут сочетать в себе как реальные закономерности, так и искажения, вызванные различием номинального и реального, причём оценить масштаб этих расхождений априори не представляется возможным — требуется проверка в каждом конкретном случае. Поскольку суть статьи сводится к описанию алгоритма и технологии, то остаётся лишь оставить здесь соответствующее предостережение для других исследователей. Потенциальными источниками «реальных» сведений могут быть, в частности, материалы открытых или частных картографических сервисов либо данные выборочных обследований Росстата.
Выводы