---
title: "Зависимость «ранг-размер» в распределении городов России по количеству юридических фирм и их работников"
author: Сёмин П. О.
output: 
  word_document:
    reference: reference.docx
bibliography: biblio.bib
csl: biblio-style.csl
---

<div custom-style="Author">

Пермский государственный национальный исследовательский университет, г. Пермь

</div>

<br>

*Аннотация:*

*Ключевые слова:*

Одной из широко известных общественно-географических закономерностей является правило «ранг-размер», также известное как закон Ципфа (Zipf's Law) [@Zipf2016]. Оно характеризует распределение городов по размеру [@Kwok2014]. Согласно правилу «ранг-размер», при ранжировании городов по убыванию численности населения, численность населения обратно пропорциональна рангу [@Rastvortseva2020]. Существуют многочисленные исследования, в которых закон Цифпа эмпирически проверяется на материале отдельных стран [@Jiang2011; @Rastvortseva2020], регионов внутри страны [@Giesen2010; @Makarova2017], нескольких стран [@Manaeva2018] или всего мира в целом [@Jiang2015] либо выступает в качестве одного из компонентов теоретической модели для анализа расселения и его изменения [@Balash2013; @Kwok2014]. В то же время интересно проверить, применимо ли правило Ципфа к другим характеристикам городов, таким как число тех или иных фирм и количество занятых в той или иной сфере деятельности, например, в юридических услугах. Теоретически это предположение не лишено оснований, так как сфера услуг тесно связана с потребностями населения, а значит, её география и сопутствующие закономерности также должны быть похожи.

В данной статье ставятся два вопроса, касающиеся географии юридических услуг в России. Первый: как связана численность населения городов и число юридических фирм и их работников? Второй: соответствует ли распределение числа юридических фирм и их работников в городах России правилу «ранг-размер»?

Для ответа на вопросы используются данные о численности населения городов России, подготовленные коммерческой аналитической фирмой «HFLabs»[^1] и набор данных о российских малых и средних юридических фирмах, собранный автором статьи. Набор данных получен с помощью самостоятельно разработанного консольного приложения на языке программирования Python *ru-smb-companies*[^2]. В качестве источника исходных сведений о фирмах выступают реестр субъектов малого и среднего предпринимательства, свободно распространяемый Федеральной налоговой службой (ФНС) Россиих[^3], а также два дополнительных набора открытых данных ФНС России: сведения о доходах и расходах организаций[^4] и сведения о среднесписочной численности работников организаций[^5]. Использованы сведения о компаниях за 2021 год. Для выбора юридических фирм из всего множества субъектов МСП осуществлена фильтрация по основному коду ОКВЭД, равному 69.10 (деятельность в области права).

[^1]: URL: https://github.com/hflabs/city (дата обращения: 12.03.2024).
[^2]: URL: https://github.com/PavelSyomin/russian-smb-companies (дата обращения: 12.03.2024).
[^3]: URL: https://www.nalog.gov.ru/opendata/7707329152-rsmp/ (дата обращения: 12.03.2024).
[^4]: URL: https://www.nalog.gov.ru/opendata/7707329152-revexp/ (дата обращения: 12.03.2024).
[^5]: URL: https://www.nalog.gov.ru/opendata/7707329152-sshr2019/ (дата обращения: 12.03.2024).

Из компаний были исключены те, которые отчитались о нулевых доходах или расходах. При нулевой отчётной численности работников предполагалось, что в компании работает один человек. Для проверки гипотез использовались линейная регрессия и визуализация данных. Формула модели линейной регрессии — $log(rank) = k \times log(count) + b + \varepsilon$. Анализ выполнен с помощью языка программирования R и дополнительных пакетов к нему. Исходный код доступен в публичном репозитории[^6].

[^6]: URL: (дата обращения: 12.03.2024).

**Литература**

<div id="refs"></div>

<div custom-style="Title">

The “Rank-Size” Rule in the Distribution of Russian Cities by the Count of Legal Companies and their Employees

</div>

<div custom-style="Author">

Syomin P. O.

Perm State University, Perm

</div>

Abstract: 

Keywords:

